name: Agente Robusto Tasa BCV
on:
  schedule:
    - cron: '0 4,10,22 * * 1-4'
    - cron: '0 4,10 * * 5'
  workflow_dispatch: 

jobs:
  actualizar:
    runs-on: ubuntu-latest
    permissions: # Esto refuerza el permiso de escritura desde el código
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Consultar y Validar Tasa
        id: bcvdata
        run: |
          RESPONSE=$(curl -s https://ve.dolarapi.com/v1/dolares/oficial)
          TASA=$(echo $RESPONSE | jq -r '.promedio')
          
          if [ "$TASA" == "null" ] || [ -z "$TASA" ]; then
            echo "Error: API falló. No se actualiza."
            exit 0
          fi
          
          # Fecha y hora Vzla
          FECHA=$(date -u -d "4 hours ago" +"%d/%m/%Y %I:%M %p")
          
          echo "{\"tasa\": \"$TASA\", \"actualizado\": \"$FECHA\"}" > tasa.json
          echo "cambio=true" >> $GITHUB_OUTPUT

      - name: Commit y Push de cambios
        if: steps.bcvdata.outputs.cambio == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Actualización Tasa BCV: ${{ steps.bcvdata.outputs.fecha }}"
          file_pattern: 'tasa.json'
